name: Linux

on:
  push:
  pull_request:
  schedule:
  #Every Sunday at midnight
  - cron:  '0 0 * * 0'

jobs:
  setup:
    name: "Setup the system"
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup Python
        uses: actions/setup-python@v2
      
      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.0.2
        
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Cache tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-cmakes
      
  install:
    name: "Install cmake packages"
    needs: setup
    runs-on: ubuntu-latest
    steps:
      
      - name: "Download cmake packages"
        run: |
            python3 -mvenv venv
            venv/bin/pip3 install -r requirements.txt
            venv/bin/python3 cmake_downloader.py --latest_patch


        
      
    
  
